# -*- coding: utf-8 -*-
"""
Created on Sun Nov  4 13:06:01 2018

@author: Mariano
"""


CONSUMER_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXx"
CONSUMER_SECRET="XXXXXXXXXXXXXXXXXXXXXXXXXx"
ACCESS_TOKEN="XXXXXXXXXXXXXXXXXXXXXXXXXx"
ACCESS_TOKEN_SECRET="XXXXXXXXXXXXXXXXXXXXXXXXXx"